CREATE TYPE "public"."user_role" AS ENUM('user', 'admin');--> statement-breakpoint
CREATE TABLE "compass_ca_cases" (
	"id" serial PRIMARY KEY NOT NULL,
	"case_id" varchar(20) NOT NULL,
	"case_status" varchar(50) DEFAULT 'incident_reported' NOT NULL,
	"employee_ohr" varchar(20) NOT NULL,
	"employee_name" varchar(255),
	"employee_pg" varchar(100),
	"employee_supervisor" varchar(255),
	"violation_category_number" integer,
	"violation_category_name" varchar(255),
	"violation_subsection" varchar(20),
	"violation_text" text,
	"violation_type" varchar(50),
	"incident_date" varchar(64),
	"incident_details" text,
	"evidence_attachments" text,
	"ai_recommended_cap_level" varchar(20),
	"ai_recommendation_reasoning" text,
	"recommended_cap_level" varchar(20),
	"final_cap_level" varchar(20),
	"cap_override_reason" text,
	"active_period_days" integer,
	"active_period_start" varchar(64),
	"active_period_end" varchar(64),
	"nte_required" boolean DEFAULT true,
	"nte_issued_date" varchar(64),
	"nte_response_deadline" varchar(64),
	"nte_response_date" varchar(64),
	"nte_response_text" text,
	"nte_document_url" text,
	"nte_signed_url" text,
	"hearing_required" boolean DEFAULT false,
	"hearing_scheduled_date" varchar(64),
	"hearing_conducted" boolean DEFAULT false,
	"hearing_notes" text,
	"nod_issued_date" varchar(64),
	"nod_decision" varchar(20),
	"nod_document_url" text,
	"cap_document_url" text,
	"cap_signed_url" text,
	"employee_signed" boolean DEFAULT false,
	"employee_signed_date" varchar(64),
	"refusal_witnessed" boolean DEFAULT false,
	"witness_names" text,
	"linked_coaching_ids" text,
	"linked_prior_case_id" varchar(20),
	"escalated_to_case_id" varchar(20),
	"created_by_ohr" varchar(20),
	"created_by_name" varchar(255),
	"notes" text,
	"created_at" varchar(64),
	"updated_at" varchar(64),
	CONSTRAINT "compass_ca_cases_case_id_unique" UNIQUE("case_id")
);
--> statement-breakpoint
CREATE TABLE "compass_ca_timeline" (
	"id" serial PRIMARY KEY NOT NULL,
	"case_id" varchar(20) NOT NULL,
	"event_type" varchar(50) NOT NULL,
	"event_date" varchar(64),
	"actor_ohr" varchar(20),
	"actor_name" varchar(255),
	"details" text,
	"attachments" text,
	"created_at" varchar(64) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "compass_coaching_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"coaching_id" varchar(20) NOT NULL,
	"coaching_type" varchar(50) NOT NULL,
	"coaching_date" varchar(64),
	"session_goals" text,
	"coaching_details" text,
	"status" varchar(100) DEFAULT 'Pending Acknowledgement',
	"coach_ohr" varchar(20),
	"coach_name" varchar(255),
	"coach_email" varchar(320),
	"coach_supervisor" varchar(255),
	"coach_supervisor_email" varchar(320),
	"coach_pg" varchar(100),
	"coachee_ohr" varchar(20),
	"coachee_name" varchar(255),
	"coachee_email" varchar(320),
	"coachee_supervisor" varchar(255),
	"coachee_supervisor_email" varchar(320),
	"coachee_pg" varchar(100),
	"sme_joiner_name" varchar(255),
	"sme_joiner_email" varchar(320),
	"sme_joiner_2_name" varchar(255),
	"sme_joiner_2_email" varchar(320),
	"job_id" varchar(100),
	"rca_level_1" varchar(255),
	"rca_level_2" varchar(255),
	"rca_level_3" varchar(255),
	"rca_level_4" varchar(255),
	"rca_level_5" varchar(255),
	"rca_description" text,
	"infraction_category" varchar(255),
	"infraction" varchar(255),
	"infraction_description" text,
	"severity" varchar(10),
	"incident_timestamp" varchar(64),
	"violation_type" varchar(255),
	"violation_subtype" text,
	"coachee_ack" boolean DEFAULT false,
	"coachee_commitments" text,
	"coaching_rating" integer,
	"coachee_sentiments" text,
	"ack_date" varchar(64),
	"parent_coaching_id" varchar(20),
	"group_session_id" varchar(20),
	"coachee_list" text,
	"linked_ca_case_id" varchar(20),
	"attachments" text,
	"week_ending" varchar(30),
	"month" varchar(30),
	"locked_by" varchar(255),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	CONSTRAINT "compass_coaching_logs_coaching_id_unique" UNIQUE("coaching_id")
);
--> statement-breakpoint
CREATE TABLE "compass_dispute_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"coaching_id" varchar(20) NOT NULL,
	"dispute_level" integer NOT NULL,
	"action" varchar(50) NOT NULL,
	"actor_ohr" varchar(20) NOT NULL,
	"actor_name" varchar(255) NOT NULL,
	"actor_role" varchar(100),
	"comments" text,
	"attachments" text,
	"created_at" varchar(64) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "compass_violation_catalog" (
	"id" serial PRIMARY KEY NOT NULL,
	"category_number" integer NOT NULL,
	"category_name" varchar(255) NOT NULL,
	"subsection" varchar(20) NOT NULL,
	"violation_code" varchar(20),
	"violation_text" text NOT NULL,
	"recommended_cap" varchar(50),
	"min_cap_level" integer DEFAULT 0,
	"max_cap_level" integer DEFAULT 3,
	"requires_nte" boolean DEFAULT true,
	"requires_hearing" boolean DEFAULT false,
	"nte_response_hours" integer DEFAULT 48
);
--> statement-breakpoint
CREATE TABLE "io_admin_ohrs" (
	"id" serial PRIMARY KEY NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"full_name" varchar(255),
	"added_by" varchar(255),
	"added_by_ohr" varchar(20),
	"added_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_attendance" (
	"id" varchar(64) PRIMARY KEY NOT NULL,
	"ohr_id" varchar(20),
	"log_date" varchar(30),
	"tag" varchar(50),
	"upl_reason" varchar(255),
	"remarks" text,
	"ot_hours" varchar(20),
	"created_at" varchar(64),
	"snap_full_name" varchar(255),
	"snap_supervisor" varchar(255),
	"snap_planning_group" varchar(100),
	"snap_shift_time" varchar(100),
	"snap_actual_role" varchar(100),
	"snap_billing_name" varchar(255),
	"snap_status" varchar(50),
	"is_locked" boolean DEFAULT false,
	"locked_at" varchar(64),
	"role" varchar(100),
	"planning_group" varchar(100),
	"internal_role" varchar(100),
	"internal_planning_group" varchar(100),
	"wfm_tag" varchar(50),
	"batch_id" varchar(50),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"record_type" varchar(50),
	"record_id" varchar(64),
	"action" varchar(50),
	"field_name" varchar(100),
	"old_value" text,
	"new_value" text,
	"actor_ohr" varchar(20),
	"actor_name" varchar(255),
	"timestamp" varchar(64),
	"metadata" text
);
--> statement-breakpoint
CREATE TABLE "io_billing_targets_v2" (
	"id" serial PRIMARY KEY NOT NULL,
	"week_ending" varchar(16) NOT NULL,
	"planning_group" varchar(100) NOT NULL,
	"role" varchar(100) NOT NULL,
	"target_hc" integer DEFAULT 0,
	"target_hours" numeric(10, 2) DEFAULT '0',
	"created_at" varchar(64),
	"updated_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_coaching" (
	"id" serial PRIMARY KEY NOT NULL,
	"coaching_id" varchar(20),
	"coaching_type" varchar(100),
	"coach" varchar(255),
	"coach_ohr" varchar(20),
	"coach_meta_email" varchar(320),
	"coach_sup" varchar(255),
	"coach_sup_email" varchar(320),
	"coach_pg" varchar(100),
	"coaching_date" varchar(64),
	"ack_date" varchar(64),
	"week_ending" varchar(30),
	"month" varchar(30),
	"coachee" varchar(255),
	"coachee_ohr" varchar(20),
	"coachee_meta_email" varchar(320),
	"coachee_sup" varchar(255),
	"coachee_sup_email" varchar(320),
	"coachee_pg" varchar(100),
	"sme_joiner" varchar(255),
	"sme_meta_email" varchar(320),
	"session_goal" text,
	"level_1_category" varchar(255),
	"level_2_direct_cause" varchar(255),
	"level_3_contributing_cause" varchar(255),
	"level_4_deficiency" varchar(255),
	"level_5_root_cause" varchar(255),
	"guidelines" text,
	"coaching_details" text,
	"status" varchar(100),
	"cap_level" varchar(50),
	"dispute_comments" text,
	"dispute_attachments" text,
	"qa_comments" text,
	"qa_attachments" text,
	"sme_qa_dispute_comments" text,
	"sme_qa_dispute_attachments" text,
	"trainer_comments" text,
	"trainer_attachments" text,
	"sme_trainer_comments" text,
	"sme_trainer_attachments" text,
	"qtp_manager_comments" text,
	"qtp_manager_attachments" text,
	"coachee_ack" text,
	"coachee_commitments" text,
	"coaching_rating" varchar(50),
	"coachee_sentiments" text,
	"attachments" text,
	"sme_dispute_stamp" varchar(64),
	"qa_decision_stamp" varchar(64),
	"sme_qa_dispute_stamp" varchar(64),
	"trainer_decision_stamp" varchar(64),
	"sme_trainer_dispute_stamp" varchar(64),
	"qtp_manager_stamp" varchar(64),
	"infraction_category" varchar(255),
	"infraction" varchar(255),
	"infraction_description" text,
	"severity" varchar(10),
	"incident_timestamp" varchar(64),
	"violation_type" varchar(255),
	"violation_subtype" text,
	"sme_joiner_2" varchar(255),
	"sme_joiner_2_email" varchar(320),
	"locked_by" varchar(255),
	"coachee_list" text,
	"job_id" varchar(100),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_coaching_nte" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"coaching_id" varchar(36) NOT NULL,
	"employee_name" varchar(255) NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"cap_level" varchar(50) NOT NULL,
	"date_of_incident" varchar(64),
	"incident_description" text,
	"policy_violated" text,
	"previous_warnings" text,
	"expected_behavior" text,
	"deadline_for_improvement" varchar(64),
	"issued_by" varchar(255),
	"issued_by_ohr" varchar(20),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_coaching_rca" (
	"id" serial PRIMARY KEY NOT NULL,
	"rca_id" varchar(50),
	"coaching_id" varchar(50),
	"level_1_category" varchar(255),
	"level_2_direct_cause" varchar(255),
	"level_3_contributing_cause" varchar(255),
	"level_4_deficiency" varchar(255),
	"level_5_root_cause" text,
	"guidelines" text,
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_coaching_ztp" (
	"id" serial PRIMARY KEY NOT NULL,
	"ztp_id" varchar(50),
	"infraction_category" varchar(255),
	"infraction" varchar(255),
	"description" text,
	"severity" varchar(10),
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_corrective_actions" (
	"id" varchar(36) PRIMARY KEY NOT NULL,
	"employee_name" varchar(255) NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"employee_email" varchar(320),
	"supervisor_name" varchar(255),
	"supervisor_ohr" varchar(20),
	"supervisor_email" varchar(320),
	"planning_group" varchar(100),
	"actual_role" varchar(100),
	"nte_type" varchar(100),
	"date_of_incident" varchar(64),
	"incident_description" text,
	"policy_violated" text,
	"violations" text,
	"response_deadline" varchar(64),
	"status" varchar(50) DEFAULT 'Served' NOT NULL,
	"served_date" varchar(64),
	"cap_level" varchar(50),
	"cap_active_days" integer,
	"cap_decision_date" varchar(64),
	"cap_decision_by" varchar(255),
	"cap_decision_by_ohr" varchar(20),
	"cap_remarks" text,
	"cap_start_date" varchar(64),
	"cap_expiry_date" varchar(64),
	"suspension_days" integer,
	"nod_issued" boolean DEFAULT false,
	"nod_date" varchar(64),
	"nod_summary" text,
	"linked_coaching_id" varchar(36),
	"attachments" text,
	"created_by" varchar(255),
	"created_by_ohr" varchar(20),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_employees" (
	"ohr_id" varchar(20) PRIMARY KEY NOT NULL,
	"full_name" varchar(255),
	"last_name" varchar(128),
	"given_name" varchar(128),
	"middle_name" varchar(128),
	"suffix" varchar(20),
	"billing_name" varchar(255),
	"srt_name" varchar(255),
	"employement_status" varchar(50),
	"actual_role" varchar(100),
	"supervisor_name" varchar(255),
	"supervisor_email" varchar(320),
	"shift_time" varchar(100),
	"work_off" varchar(100),
	"planning_group" varchar(100),
	"complete_planning_group" text,
	"srt_status" varchar(50),
	"srt_id" varchar(50),
	"workday_id" varchar(50),
	"meta_email" varchar(320),
	"macbook_asset_id" varchar(50),
	"chromebook_asset_id" varchar(50),
	"hire_date" varchar(30),
	"regular_date" varchar(30),
	"dob" varchar(30),
	"personal_email" varchar(320),
	"contact_number" varchar(50),
	"primary_address" text,
	"barangay" varchar(128),
	"city" varchar(128),
	"province" varchar(128),
	"locker_floor" varchar(20),
	"locker_number" varchar(20),
	"meta_onboarding_date" varchar(30),
	"live_date" varchar(30),
	"badge_id" varchar(50),
	"badge_serial" varchar(50),
	"platform" varchar(100),
	"gchat_space_id" varchar(100),
	"offboarding_date" varchar(30),
	"resignation_date" varchar(30),
	"relieving_date" varchar(30),
	"exit_date" varchar(30),
	"exit_reason" varchar(255),
	"department" varchar(128),
	"floor" varchar(10),
	"sex" varchar(2),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_gchat_queue" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" varchar(100) NOT NULL,
	"target_space_id" varchar(100),
	"target_name" varchar(255),
	"card_json" text NOT NULL,
	"fallback_text" text,
	"status" varchar(20) DEFAULT 'pending',
	"metadata" text,
	"created_at" varchar(64),
	"sent_at" varchar(64),
	"error_message" text
);
--> statement-breakpoint
CREATE TABLE "io_group_tasks" (
	"id" serial PRIMARY KEY NOT NULL,
	"task_id" varchar(20) NOT NULL,
	"title" varchar(500) NOT NULL,
	"description" text,
	"category" varchar(100),
	"planning_groups" text,
	"departments" text,
	"roles" text,
	"excluded_ohrs" text,
	"due_date" varchar(64),
	"status" varchar(50) DEFAULT 'Active',
	"created_by_ohr" varchar(20) NOT NULL,
	"created_by_name" varchar(255),
	"created_at" varchar(64),
	"updated_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_insights" (
	"id" serial PRIMARY KEY NOT NULL,
	"insight_id" varchar(50),
	"insight_title" varchar(500),
	"status" varchar(255),
	"meta_email" varchar(320),
	"submitter" varchar(255),
	"ohr_id" varchar(20),
	"week_ending" varchar(30),
	"supervisor" varchar(255),
	"supervisor_email" varchar(320),
	"planning_group" varchar(100),
	"insight_category" varchar(100),
	"proposal_type" varchar(100),
	"platform" varchar(100),
	"implementation_standards" varchar(255),
	"queue" varchar(255),
	"problem_statement" text,
	"proposed_change" text,
	"job_id_1" text,
	"job_id_2" text,
	"job_id_3" text,
	"job_id_4" text,
	"job_id_5" text,
	"job_id_6" text,
	"job_id_7" text,
	"job_id_8" text,
	"job_id_9" text,
	"job_id_10" text,
	"impact" text,
	"reach" text,
	"created_date" varchar(64),
	"ir_update_date" varchar(64),
	"tr_update_date" varchar(64),
	"implementation_date" varchar(64),
	"initial_reviewer" varchar(255),
	"initial_review_date" varchar(64),
	"initial_review_comments" text,
	"initial_reviewer_comments" text,
	"final_reviewer" varchar(255),
	"final_review_date" varchar(64),
	"final_review_comments" text,
	"trainer" varchar(255),
	"trainer_comments" text,
	"attachments" text,
	"task_id" varchar(100),
	"month" varchar(30),
	"locked_by" varchar(255),
	"batch_id" varchar(50),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_leave_periods" (
	"id" serial PRIMARY KEY NOT NULL,
	"month" integer NOT NULL,
	"year" integer NOT NULL,
	"start_week_ending" varchar(10) NOT NULL,
	"created_by" varchar(255),
	"created_by_ohr" varchar(20),
	"created_at" varchar(64),
	"updated_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_leaves" (
	"id" serial PRIMARY KEY NOT NULL,
	"leave_id" varchar(50),
	"leave_type" varchar(100),
	"status" varchar(100),
	"ohr_id" varchar(20),
	"full_name" varchar(255),
	"meta_email" varchar(320),
	"supervisor" varchar(255),
	"supervisor_email" varchar(320),
	"planning_group" varchar(100),
	"start_date" varchar(30),
	"end_date" varchar(30),
	"reason" text,
	"remarks" text,
	"approver_comments" text,
	"attachments" text,
	"tl_reviewer" varchar(255),
	"tl_review_date" varchar(64),
	"om_reviewer" varchar(255),
	"om_review_date" varchar(64),
	"rejection_reason" text,
	"cancelled_at" varchar(64),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_notifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"type" varchar(50),
	"title" varchar(255),
	"message" text,
	"actor_ohr" varchar(20),
	"actor_name" varchar(255),
	"target_role" varchar(50),
	"target_ohr" varchar(20),
	"metadata" text,
	"is_read" boolean DEFAULT false,
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_permissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"permission_key" varchar(100) NOT NULL,
	"granted" boolean DEFAULT false NOT NULL,
	"updated_by" varchar(20),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "io_productivity_hours" (
	"id" serial PRIMARY KEY NOT NULL,
	"date" varchar(16) NOT NULL,
	"ohr" varchar(32) NOT NULL,
	"actual_projection" varchar(32) DEFAULT 'Actuals',
	"available" numeric(8, 2) DEFAULT '0',
	"non_srt_production" numeric(8, 2) DEFAULT '0',
	"fb_training" numeric(8, 2) DEFAULT '0',
	"onboarding" numeric(8, 2) DEFAULT '0',
	"coaching" numeric(8, 2) DEFAULT '0',
	"wellness_support" numeric(8, 2) DEFAULT '0',
	"team_meeting" numeric(8, 2) DEFAULT '0',
	"total_billable" numeric(8, 2) DEFAULT '0',
	"delivered_hours" numeric(8, 2) DEFAULT '0',
	"uploaded_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_role_changes" (
	"id" serial PRIMARY KEY NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"srt_id" varchar(50),
	"employee_name" varchar(255) NOT NULL,
	"original_role" varchar(100) NOT NULL,
	"original_pg" varchar(100) NOT NULL,
	"new_role" varchar(100) NOT NULL,
	"new_pg" varchar(100) NOT NULL,
	"date_from" varchar(10) NOT NULL,
	"date_to" varchar(10) NOT NULL,
	"week_ending" varchar(10) NOT NULL,
	"created_by" varchar(255),
	"created_by_ohr" varchar(20),
	"email_generated_at" varchar(64),
	"attendance_updated" boolean DEFAULT false,
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_shift_extensions" (
	"id" serial PRIMARY KEY NOT NULL,
	"request_id" varchar(20),
	"agent_ohr" varchar(20),
	"agent_name" varchar(255),
	"supervisor_ohr" varchar(20),
	"supervisor_name" varchar(255),
	"planning_group" varchar(100),
	"shift_date" varchar(30),
	"extension_minutes" integer,
	"reason_details" text,
	"tl_status" varchar(30),
	"tl_comments" text,
	"tl_actioned_by" varchar(255),
	"tl_actioned_at" varchar(64),
	"om_status" varchar(30),
	"om_comments" text,
	"om_actioned_by" varchar(255),
	"om_actioned_at" varchar(64),
	"overall_status" varchar(30),
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_srt_bill" (
	"id" serial PRIMARY KEY NOT NULL,
	"date" varchar(16) NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"srt_id" varchar(50),
	"billing_name" varchar(255),
	"srt_status" varchar(50),
	"role" varchar(100),
	"planning_group" varchar(100),
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_sync_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"sync_type" varchar(50) NOT NULL,
	"trigger" varchar(50) NOT NULL,
	"status" varchar(20) NOT NULL,
	"started_at" varchar(64) NOT NULL,
	"completed_at" varchar(64),
	"duration_ms" integer,
	"rows_updated" integer DEFAULT 0,
	"rows_appended" integer DEFAULT 0,
	"total_db_rows" integer DEFAULT 0,
	"total_sheet_rows" integer DEFAULT 0,
	"error_message" text,
	"output_log" text
);
--> statement-breakpoint
CREATE TABLE "io_tardiness" (
	"id" serial PRIMARY KEY NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"employee_name" varchar(255) NOT NULL,
	"supervisor_name" varchar(255),
	"planning_group" varchar(100),
	"actual_role" varchar(100),
	"shift_time" varchar(100),
	"date" varchar(16) NOT NULL,
	"roster_login" varchar(30),
	"roster_logout" varchar(30),
	"actual_login" varchar(30),
	"actual_logout" varchar(30),
	"tardiness_minutes" integer DEFAULT 0 NOT NULL,
	"shift_type" varchar(30),
	"week_ending" varchar(16) NOT NULL,
	"validation_status" varchar(20) DEFAULT 'Pending' NOT NULL,
	"validated_by" varchar(255),
	"validated_by_ohr" varchar(20),
	"validated_at" varchar(64),
	"remarks" text,
	"upload_batch" varchar(64),
	"created_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_task_assignments" (
	"id" serial PRIMARY KEY NOT NULL,
	"group_task_id" integer NOT NULL,
	"employee_ohr" varchar(20) NOT NULL,
	"employee_name" varchar(255),
	"status" varchar(50) DEFAULT 'Pending',
	"completed_at" varchar(64),
	"attachment_url" text,
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_task_comments" (
	"id" serial PRIMARY KEY NOT NULL,
	"task_id" varchar(20),
	"author_ohr" varchar(20),
	"author_name" varchar(255),
	"content" text,
	"attachments" text,
	"created_at" varchar(64)
);
--> statement-breakpoint
CREATE TABLE "io_tasks" (
	"id" serial PRIMARY KEY NOT NULL,
	"task_id" varchar(20),
	"title" varchar(500),
	"description" text,
	"status" varchar(100),
	"assigned_to_ohr" text,
	"assigned_to_name" text,
	"assigned_to_pg" text,
	"assigned_by_ohr" varchar(20),
	"assigned_by_name" varchar(255),
	"due_date" varchar(64),
	"completed_date" varchar(64),
	"record_type" varchar(50) DEFAULT 'task',
	"request_type" varchar(100),
	"approval_status" varchar(50),
	"attachments" text,
	"created_at" varchar(64),
	"updated_at" varchar(64),
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "io_wfm_schedules" (
	"id" serial PRIMARY KEY NOT NULL,
	"ohr_id" varchar(20) NOT NULL,
	"schedule_date" varchar(10) NOT NULL,
	"wfm_value" varchar(50) NOT NULL,
	"uploaded_at" varchar(64),
	"uploaded_by" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE TABLE "wfm_session_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"login_at" varchar(64) NOT NULL,
	"ip_address" varchar(64),
	"user_agent" text,
	"action" varchar(50) DEFAULT 'login',
	"details" text
);
