CREATE TABLE `io_attendance` (
	`id` varchar(64) NOT NULL,
	`ohr_id` varchar(20),
	`log_date` varchar(30),
	`tag` varchar(50),
	`billing_code` varchar(100),
	`upl_reason` varchar(255),
	`remarks` text,
	`ot_hours` varchar(20),
	`created_at` varchar(64),
	`snap_full_name` varchar(255),
	`snap_supervisor` varchar(255),
	`snap_planning_group` varchar(100),
	`snap_shift_time` varchar(100),
	`snap_actual_role` varchar(100),
	`snap_billing_name` varchar(255),
	`snap_status` varchar(50),
	`is_locked` boolean DEFAULT false,
	`locked_at` varchar(64),
	CONSTRAINT `io_attendance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`record_type` varchar(50),
	`record_id` varchar(64),
	`action` varchar(50),
	`field_name` varchar(100),
	`old_value` text,
	`new_value` text,
	`actor_ohr` varchar(20),
	`actor_name` varchar(255),
	`timestamp` varchar(64),
	`metadata` text,
	CONSTRAINT `io_audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_coaching` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coaching_id` varchar(20),
	`coaching_type` varchar(100),
	`coach` varchar(255),
	`coach_ohr` varchar(20),
	`coach_meta_email` varchar(320),
	`coach_sup` varchar(255),
	`coach_sup_email` varchar(320),
	`coach_pg` varchar(100),
	`coaching_date` varchar(64),
	`ack_date` varchar(64),
	`week_ending` varchar(30),
	`month` varchar(30),
	`coachee` varchar(255),
	`coachee_ohr` varchar(20),
	`coachee_meta_email` varchar(320),
	`coachee_sup` varchar(255),
	`coachee_sup_email` varchar(320),
	`coachee_pg` varchar(100),
	`sme_joiner` varchar(255),
	`sme_meta_email` varchar(320),
	`session_goal` text,
	`level_1_category` varchar(255),
	`level_2_direct_cause` varchar(255),
	`level_3_contributing_cause` varchar(255),
	`level_4_deficiency` varchar(255),
	`level_5_root_cause` varchar(255),
	`guidelines` text,
	`coaching_details` text,
	`status` varchar(100),
	`dispute_comments` text,
	`dispute_attachments` text,
	`qa_comments` text,
	`qa_attachments` text,
	`sme_qa_dispute_comments` text,
	`sme_qa_dispute_attachments` text,
	`trainer_comments` text,
	`trainer_attachments` text,
	`sme_trainer_comments` text,
	`sme_trainer_attachments` text,
	`qtp_manager_comments` text,
	`qtp_manager_attachments` text,
	`coachee_ack` text,
	`coachee_commitments` text,
	`coaching_rating` varchar(50),
	`coachee_sentiments` text,
	`attachments` text,
	`sme_dispute_stamp` varchar(64),
	`qa_decision_stamp` varchar(64),
	`sme_qa_dispute_stamp` varchar(64),
	`trainer_decision_stamp` varchar(64),
	`sme_trainer_dispute_stamp` varchar(64),
	`qtp_manager_stamp` varchar(64),
	`infraction_category` varchar(255),
	`infraction` varchar(255),
	`infraction_description` text,
	`severity` varchar(10),
	`locked_by` varchar(255),
	`coachee_list` text,
	`job_id` varchar(100),
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `io_coaching_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_coaching_rca` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rca_id` varchar(50),
	`coaching_id` varchar(50),
	`level_1_category` varchar(255),
	`level_2_direct_cause` varchar(255),
	`level_3_contributing_cause` varchar(255),
	`level_4_deficiency` varchar(255),
	`level_5_root_cause` text,
	`guidelines` text,
	`created_at` varchar(64),
	CONSTRAINT `io_coaching_rca_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_coaching_ztp` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ztp_id` varchar(50),
	`infraction_category` varchar(255),
	`infraction` varchar(255),
	`description` text,
	`severity` varchar(10),
	`created_at` varchar(64),
	CONSTRAINT `io_coaching_ztp_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_employees` (
	`ohr_id` varchar(20) NOT NULL,
	`full_name` varchar(255),
	`access_level` int,
	`last_name` varchar(128),
	`given_name` varchar(128),
	`middle_name` varchar(128),
	`suffix` varchar(20),
	`billing_name` varchar(255),
	`srt_name` varchar(255),
	`employement_status` varchar(50),
	`actual_role` varchar(100),
	`supervisor_name` varchar(255),
	`supervisor_email` varchar(320),
	`shift_time` varchar(100),
	`work_off` varchar(100),
	`planning_group` varchar(100),
	`complete_planning_group` text,
	`srt_status` varchar(50),
	`srt_id` varchar(50),
	`workday_id` varchar(50),
	`meta_email` varchar(320),
	`macbook_asset_id` varchar(50),
	`chromebook_asset_id` varchar(50),
	`hire_date` varchar(30),
	`regular_date` varchar(30),
	`dob` varchar(30),
	`personal_email` varchar(320),
	`contact_number` varchar(50),
	`primary_address` text,
	`barangay` varchar(128),
	`city` varchar(128),
	`province` varchar(128),
	`locker_floor` varchar(20),
	`locker_number` varchar(20),
	`meta_onboarding_date` varchar(30),
	`live_date` varchar(30),
	`badge_id` varchar(50),
	`badge_serial` varchar(50),
	`platform` varchar(100),
	`billing_code` varchar(100),
	`password` varchar(255),
	`is_locked` boolean DEFAULT false,
	CONSTRAINT `io_employees_ohr_id` PRIMARY KEY(`ohr_id`)
);
--> statement-breakpoint
CREATE TABLE `io_insights` (
	`id` int AUTO_INCREMENT NOT NULL,
	`insight_id` varchar(50),
	`insight_title` varchar(500),
	`status` varchar(255),
	`meta_email` varchar(320),
	`submitter` varchar(255),
	`ohr_id` varchar(20),
	`week_ending` varchar(30),
	`supervisor` varchar(255),
	`supervisor_email` varchar(320),
	`planning_group` varchar(100),
	`insight_category` varchar(100),
	`proposal_type` varchar(100),
	`platform` varchar(100),
	`implementation_standards` varchar(255),
	`queue` varchar(255),
	`problem_statement` text,
	`proposed_change` text,
	`job_id_1` text,
	`job_id_2` text,
	`job_id_3` text,
	`job_id_4` text,
	`job_id_5` text,
	`job_id_6` text,
	`job_id_7` text,
	`job_id_8` text,
	`job_id_9` text,
	`job_id_10` text,
	`impact` text,
	`reach` text,
	`created_date` varchar(64),
	`ir_update_date` varchar(64),
	`tr_update_date` varchar(64),
	`implementation_date` varchar(64),
	`initial_reviewer` varchar(255),
	`initial_reviewer_comments` text,
	`trainer` varchar(255),
	`trainer_comments` text,
	`attachments` text,
	`task_id` varchar(100),
	`month` varchar(30),
	`locked_by` varchar(255),
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `io_insights_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_leaves` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leave_id` varchar(50),
	`leave_type` varchar(100),
	`status` varchar(100),
	`ohr_id` varchar(20),
	`full_name` varchar(255),
	`meta_email` varchar(320),
	`supervisor` varchar(255),
	`supervisor_email` varchar(320),
	`planning_group` varchar(100),
	`start_date` varchar(30),
	`end_date` varchar(30),
	`reason` text,
	`remarks` text,
	`approver_comments` text,
	`attachments` text,
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `io_leaves_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_notifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` varchar(50),
	`title` varchar(255),
	`message` text,
	`actor_ohr` varchar(20),
	`actor_name` varchar(255),
	`target_role` varchar(50),
	`target_ohr` varchar(20),
	`metadata` text,
	`is_read` boolean DEFAULT false,
	`created_at` varchar(64),
	CONSTRAINT `io_notifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_task_comments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`task_id` varchar(20),
	`author_ohr` varchar(20),
	`author_name` varchar(255),
	`content` text,
	`attachments` text,
	`created_at` varchar(64),
	CONSTRAINT `io_task_comments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `io_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`task_id` varchar(20),
	`title` varchar(500),
	`description` text,
	`status` varchar(100),
	`priority` varchar(20),
	`assigned_to_ohr` varchar(20),
	`assigned_to_name` varchar(255),
	`assigned_to_pg` varchar(100),
	`assigned_by_ohr` varchar(20),
	`assigned_by_name` varchar(255),
	`due_date` varchar(64),
	`completed_date` varchar(64),
	`target_entity` varchar(100),
	`target_entity_id` varchar(100),
	`attachments` text,
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `io_tasks_id` PRIMARY KEY(`id`)
);
