CREATE TABLE `compass_ca_cases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`case_id` varchar(20) NOT NULL,
	`case_status` varchar(50) NOT NULL DEFAULT 'incident_reported',
	`employee_ohr` varchar(20) NOT NULL,
	`employee_name` varchar(255),
	`employee_pg` varchar(100),
	`employee_supervisor` varchar(255),
	`violation_category_number` int,
	`violation_category_name` varchar(255),
	`violation_subsection` varchar(20),
	`violation_text` text,
	`violation_type` varchar(50),
	`incident_date` varchar(64),
	`incident_details` text,
	`evidence_attachments` text,
	`ai_recommended_cap_level` varchar(20),
	`ai_recommendation_reasoning` text,
	`recommended_cap_level` varchar(20),
	`final_cap_level` varchar(20),
	`cap_override_reason` text,
	`active_period_days` int,
	`active_period_start` varchar(64),
	`active_period_end` varchar(64),
	`nte_required` boolean DEFAULT true,
	`nte_issued_date` varchar(64),
	`nte_response_deadline` varchar(64),
	`nte_response_date` varchar(64),
	`nte_response_text` text,
	`nte_document_url` text,
	`nte_signed_url` text,
	`hearing_required` boolean DEFAULT false,
	`hearing_scheduled_date` varchar(64),
	`hearing_conducted` boolean DEFAULT false,
	`hearing_notes` text,
	`nod_issued_date` varchar(64),
	`nod_decision` varchar(20),
	`nod_document_url` text,
	`cap_document_url` text,
	`cap_signed_url` text,
	`employee_signed` boolean DEFAULT false,
	`employee_signed_date` varchar(64),
	`refusal_witnessed` boolean DEFAULT false,
	`witness_names` text,
	`linked_coaching_ids` text,
	`linked_prior_case_id` varchar(20),
	`escalated_to_case_id` varchar(20),
	`created_by_ohr` varchar(20),
	`created_by_name` varchar(255),
	`notes` text,
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `compass_ca_cases_id` PRIMARY KEY(`id`),
	CONSTRAINT `compass_ca_cases_case_id_unique` UNIQUE(`case_id`)
);
--> statement-breakpoint
CREATE TABLE `compass_ca_timeline` (
	`id` int AUTO_INCREMENT NOT NULL,
	`case_id` varchar(20) NOT NULL,
	`event_type` varchar(50) NOT NULL,
	`event_date` varchar(64),
	`actor_ohr` varchar(20),
	`actor_name` varchar(255),
	`details` text,
	`attachments` text,
	`created_at` varchar(64) NOT NULL,
	CONSTRAINT `compass_ca_timeline_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compass_coaching_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coaching_id` varchar(20) NOT NULL,
	`coaching_type` varchar(50) NOT NULL,
	`coaching_date` varchar(64),
	`session_goals` text,
	`coaching_details` text,
	`status` varchar(100) DEFAULT 'Pending Acknowledgement',
	`coach_ohr` varchar(20),
	`coach_name` varchar(255),
	`coach_email` varchar(320),
	`coach_supervisor` varchar(255),
	`coach_supervisor_email` varchar(320),
	`coach_pg` varchar(100),
	`coachee_ohr` varchar(20),
	`coachee_name` varchar(255),
	`coachee_email` varchar(320),
	`coachee_supervisor` varchar(255),
	`coachee_supervisor_email` varchar(320),
	`coachee_pg` varchar(100),
	`sme_joiner_name` varchar(255),
	`sme_joiner_email` varchar(320),
	`job_id` varchar(100),
	`rca_level_1` varchar(255),
	`rca_level_2` varchar(255),
	`rca_level_3` varchar(255),
	`rca_level_4` varchar(255),
	`rca_level_5` varchar(255),
	`rca_description` text,
	`infraction_category` varchar(255),
	`infraction` varchar(255),
	`infraction_description` text,
	`severity` varchar(10),
	`coachee_ack` boolean DEFAULT false,
	`coachee_commitments` text,
	`coaching_rating` int,
	`coachee_sentiments` text,
	`ack_date` varchar(64),
	`parent_coaching_id` varchar(20),
	`group_session_id` varchar(20),
	`coachee_list` text,
	`linked_ca_case_id` varchar(20),
	`attachments` text,
	`week_ending` varchar(30),
	`month` varchar(30),
	`locked_by` varchar(255),
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `compass_coaching_logs_id` PRIMARY KEY(`id`),
	CONSTRAINT `compass_coaching_logs_coaching_id_unique` UNIQUE(`coaching_id`)
);
--> statement-breakpoint
CREATE TABLE `compass_dispute_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`coaching_id` varchar(20) NOT NULL,
	`dispute_level` int NOT NULL,
	`action` varchar(50) NOT NULL,
	`actor_ohr` varchar(20) NOT NULL,
	`actor_name` varchar(255) NOT NULL,
	`actor_role` varchar(100),
	`comments` text,
	`attachments` text,
	`created_at` varchar(64) NOT NULL,
	CONSTRAINT `compass_dispute_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `compass_violation_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`category_number` int NOT NULL,
	`category_name` varchar(255) NOT NULL,
	`subsection` varchar(20) NOT NULL,
	`violation_code` varchar(20),
	`violation_text` text NOT NULL,
	`recommended_cap` varchar(50),
	`min_cap_level` int DEFAULT 0,
	`max_cap_level` int DEFAULT 3,
	`requires_nte` boolean DEFAULT true,
	`requires_hearing` boolean DEFAULT false,
	`nte_response_hours` int DEFAULT 48,
	CONSTRAINT `compass_violation_catalog_id` PRIMARY KEY(`id`)
);
