CREATE TABLE `io_corrective_actions` (
	`id` varchar(36) NOT NULL,
	`employee_name` varchar(255) NOT NULL,
	`ohr_id` varchar(20) NOT NULL,
	`employee_email` varchar(320),
	`supervisor_name` varchar(255),
	`supervisor_ohr` varchar(20),
	`supervisor_email` varchar(320),
	`planning_group` varchar(100),
	`actual_role` varchar(100),
	`nte_type` varchar(100),
	`date_of_incident` varchar(64),
	`incident_description` text,
	`policy_violated` text,
	`violations` text,
	`response_deadline` varchar(64),
	`status` varchar(50) NOT NULL DEFAULT 'Served',
	`served_date` varchar(64),
	`cap_level` varchar(50),
	`cap_active_days` int,
	`cap_decision_date` varchar(64),
	`cap_decision_by` varchar(255),
	`cap_decision_by_ohr` varchar(20),
	`cap_remarks` text,
	`cap_start_date` varchar(64),
	`cap_expiry_date` varchar(64),
	`suspension_days` int,
	`nod_issued` boolean DEFAULT false,
	`nod_date` varchar(64),
	`nod_summary` text,
	`linked_coaching_id` varchar(36),
	`attachments` text,
	`created_by` varchar(255),
	`created_by_ohr` varchar(20),
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `io_corrective_actions_id` PRIMARY KEY(`id`)
);
