CREATE TABLE `io_tardiness` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ohr_id` varchar(20) NOT NULL,
	`employee_name` varchar(255) NOT NULL,
	`supervisor_name` varchar(255),
	`planning_group` varchar(100),
	`actual_role` varchar(100),
	`shift_time` varchar(100),
	`date` varchar(16) NOT NULL,
	`roster_login` varchar(30),
	`roster_logout` varchar(30),
	`actual_login` varchar(30),
	`actual_logout` varchar(30),
	`tardiness_minutes` int NOT NULL DEFAULT 0,
	`shift_type` varchar(30),
	`week_ending` varchar(16) NOT NULL,
	`validation_status` varchar(20) NOT NULL DEFAULT 'Pending',
	`validated_by` varchar(255),
	`validated_by_ohr` varchar(20),
	`validated_at` varchar(64),
	`remarks` text,
	`upload_batch` varchar(64),
	`created_at` varchar(64),
	CONSTRAINT `io_tardiness_id` PRIMARY KEY(`id`)
);
