CREATE TABLE `io_shift_extensions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_id` varchar(20),
	`agent_ohr` varchar(20),
	`agent_name` varchar(255),
	`supervisor_ohr` varchar(20),
	`supervisor_name` varchar(255),
	`planning_group` varchar(100),
	`shift_date` varchar(30),
	`extension_minutes` int,
	`reason_details` text,
	`tl_status` varchar(30),
	`tl_comments` text,
	`tl_actioned_by` varchar(255),
	`tl_actioned_at` varchar(64),
	`om_status` varchar(30),
	`om_comments` text,
	`om_actioned_by` varchar(255),
	`om_actioned_at` varchar(64),
	`overall_status` varchar(30),
	`created_at` varchar(64),
	`updated_at` varchar(64),
	CONSTRAINT `io_shift_extensions_id` PRIMARY KEY(`id`)
);
